postsubmits:
  # this is the github repo we'll build from; this block needs to be repeated for each repo.
  kubernetes/kops:
    - name: kops-postsubmit-push-to-staging
      cluster: k8s-infra-prow-build-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-kops, kops-misc
      decorate: true
      branches:
        - ^master$
        - ^release-.*
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200612-cd781f9
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-kops
              - --scratch-bucket=gs://k8s-staging-kops-gcb
              - --env-passthrough=PULL_BASE_REF
              - --with-git-dir
              - .
