# To copy an image between projects:
# `gcloud compute --project <to-project> disks create <image name> --image=https://www.googleapis.com/compute/v1/projects/<from-project>/global/images/<image-name>`
# `gcloud compute --project <to-project> images create <image-name> --source-disk=<image-name>`
images:
  ubuntu:
    image: ubuntu-gke-1804-1-16-v20200330 # docker 17.03
    project: ubuntu-os-gke-cloud
    # Using `n1-standard-4` to enable CPU manager node e2e tests.
    machine: n1-standard-4
  cos-stable1:
    image: cos-77-12371-274-0 # docker v19.03.1, deprecated after 2020-12-17
    project: cos-cloud
    metadata: "user-data<test/e2e_node/jenkins/cos-init-live-restore.yaml,gci-update-strategy=update_disabled"
    # Using `n1-standard-4` to enable CPU manager node e2e tests.
    machine: n1-standard-4
