periodics:
- name: ci-k8sio-groups
  interval: 24h
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  annotations:
    testgrid-dashboards: wg-k8s-infra-k8sio
    testgrid-alert-email: k8s-infra-alerts@kubernetes.io
    testgrid-num-failures-to-alert: '1'
  max_concurrency: 1
  extra_refs:
  - org: kubernetes
    repo: k8s.io
    base_ref: master
  spec:
    serviceAccountName: gsuite-groups-manager
    containers:
    - name: groups
      image: golang:1.13
      command:
      - bash
      args:
      - -c
      - "cd groups && make run -- --confirm"

postsubmits:
  kubernetes/k8s.io:
  - name: post-k8sio-groups
    cluster: k8s-infra-prow-build-trusted
    decorate: true
    run_if_changed: '^groups/groups.yaml'
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: wg-k8s-infra-k8sio
      testgrid-alert-email: k8s-infra-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
    spec:
      serviceAccountName: gsuite-groups-manager
      containers:
      - name: groups
        image: golang:1.13
        command:
        - bash
        args:
        - -c
        - "cd groups && make run -- --confirm"
  - name: post-k8sio-dns-update
    cluster: k8s-infra-prow-build-trusted
    decorate: true
    run_if_changed: "^dns/zone-configs/"
    max_concurrency: 1
    branches:
    - ^master$
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: wg-k8s-infra-k8sio
      testgrid-alert-email: k8s-infra-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
    spec:
      serviceAccountName: k8s-infra-dns-updater
      containers:
      - image: us.gcr.io/k8s-artifacts-prod/infra-tools/octodns:v20200616-67ce585
        command:
        - bash
        args:
        - -c
        - "cd dns && make dry-run-local"
