# sigs.k8s.io/descheduler presubmits
presubmits:
  kubernetes-sigs/descheduler:
  - name: pull-descheduler-verify-release-1-17
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-descheduler-verify-release-1.17
    decorate: true
    path_alias: sigs.k8s.io/descheduler
    branches:
    # The script this job runs is not in all branches.
    - ^release-1.17$
    always_run: true
    spec:
      containers:
      - image: golang:1.13
        command:
        - make
        args:
        - verify
  - name: pull-descheduler-verify-build-release-1-17
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-descheduler-verify-build-release-1.17
    decorate: true
    path_alias: sigs.k8s.io/descheduler
    branches:
    # The script this job runs is not in all branches.
    - ^release-1.17$
    always_run: true
    spec:
      containers:
      - image: golang:1.13
        command:
        - make
        args:
        - build
  - name: pull-descheduler-unit-test-release-1-17
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-descheduler-unit-test-release-1.17
    decorate: true
    path_alias: sigs.k8s.io/descheduler
    branches:
    # The script this job runs is not in all branches.
    - ^release-1.17$
    always_run: true
    spec:
      containers:
      - image: golang:1.13
        command:
        - make
        args:
        - test-unit
